### ISSUE TITLE
Corrock is waterlogged upon conversion

### ISSUE THREAD

**Issue by Boneful** [minecraftabnormals/The-Endergetic-Expansion#220]
Corrock plants are immediately waterlogged upon conversion. Works for all corrock plants in all dimensions, as a side effect, allowing water in the nether.
Example
![2022-08-22_21 39 45](https://user-images.githubusercontent.com/55305072/186071523-91c47b97-d4c2-4745-9146-9b0eb1bdafed.png)
![2022-08-22_21 39 50](https://user-images.githubusercontent.com/55305072/186071531-fa734e00-3862-4e47-9f35-02c715bc607d.png)

Applies to 1.16.5 (not tested on other versions)

**Comment by SmellyModder** [comment]
Corrock is an unfinished feature in 1.16.5, so any bugs with it on public 1.16.5 versions are very minor.
I will see if the issue still happens on 1.19.

**Comment by murao-kun** [comment]
This issue is not happening in 1.19. But I noticed that waterlogged variants do not convert to their dimension variant.
It is staying as nether variant for like 3 minutes. Non-waterlogged variants converts fine.
![image](https://user-images.githubusercontent.com/110398598/197784234-726ff664-72ad-471b-9c60-4a217a97a36c.png)

**Comment by SmellyModder** [comment]
That feature is intentional. Corrock that gets touched by water becomes Petrified Corrock.

**Comment by murao-kun** [comment]
Oh. That means that there is no issue in 1.19 at all then.

**Comment by SmellyModder** [comment]
Just going to close this issue because Corrock is incomplete on 1.16.5, and this issue is not prevalent on 1.19.
