### ISSUE TITLE
Inflated booflo doesn't do eating animation when swallowing puff bug

### ISSUE THREAD

**Issue by generrosity** [minecraftabnormals/The-Endergetic-Expansion#77]
Version: beta3 (1.16.1)

Requested that Mothron replicated the fault and describe. 

 Mothron CEO of moth cult: i just saw, booflo swallowed a puff bug while inflated
 Mothron CEO of moth cult: whitout doing the eating animation
 Mothron CEO of moth cult: not sure if he'll do it once landing somewhere

Issue for tracking purposes

**Comment by SmellyModder** [comment]
Not an issue, sorta intentional. 
The Booflo takes a bit of time to open its mouth when trying to swallow something, so it's likely the Booflo got to the Puff Bug before it could play its mouth opening animation.
This won't affect any of the AI after either, as the Booflo animation is just client-side and starts playing when it has a target.

**Comment by generrosity** [comment]
Sweet - so they get swollowed whole instead of chewed. I'll update the wiki with that ;)
